networks:
  kafka:

services:
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka_broker
    networks:
      - kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    healthcheck:
      test: [ "CMD-SHELL", "kafka-cluster.sh cluster-id --bootstrap-server localhost:9092 || exit 1" ]
      start_period: 10s
      interval: 5s
      timeout: 15s
      retries: 5

  producer:
    container_name: producer
    build:
      context: ./producer
    networks:
      - kafka
    volumes:
      - "./producer:/producer"
    depends_on:
      kafka:
        condition: service_healthy

  consumer:
    container_name: consumer
    build:
      context: ./consumer
    networks:
      - kafka
    volumes:
      - "./consumer:/consumer"
    depends_on:
      kafka:
        condition: service_healthy